# Generated by Django 5.0.3 on 2024-03-28 14:44

import files.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.utils.upload_to)),
                ('file_binary', models.BinaryField(blank=True, null=True)),
                ('storage_type', models.CharField(choices=[('disk', 'Disk'), ('db', 'DB')], max_length=4)),
            ],
        ),
    ]
